# Generated by Django 5.2 on 2025-04-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_financial_advisor_user_is_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='annual_income',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='familiarity_with_market',
            field=models.IntegerField(choices=[(0, 'Not familiar at all'), (1, 'Somewhat familiar'), (2, 'Moderately familiar'), (3, 'Very familiar'), (4, 'Expert level familiarity')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='percentage_comforatable_savings',
            field=models.IntegerField(choices=[(0, '0-5% of Income'), (1, '5-10% of Income'), (2, '10-15% of Income'), (3, '15-20% of Income'), (4, '20%-100% of Income')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='primary_investment_goal',
            field=models.CharField(choices=[('protecting_your_principal', 'Protecting Your Principal'), ('income_generation', 'Income Generation'), ('balanced_growth_and_income', 'Balanced Growth and Income'), ('Growth_oriented_investing', 'Growth-Oriented Investing'), ('aggressive_growth', 'Aggressive Growth')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='investment_horizon_years',
            field=models.IntegerField(choices=[(0, 'Less than 1 year'), (1, '1 to 3 years'), (2, '3 to 5 years'), (3, '5 to 10 years'), (4, 'More than 10 years')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='financial_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
