# Generated by Django 5.2 on 2025-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientprofile_age_clientprofile_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='investment_horizon_years',
            field=models.IntegerField(choices=[(12, 'Less than 1 year'), (36, '1 to 3 years'), (60, '3 to 5 years'), (120, '5 to 10 years'), (240, 'More than 10 years')]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='percentage_comforatable_savings',
            field=models.IntegerField(choices=[(3, '0-5% of Income'), (8, '5-10% of Income'), (13, '10-15% of Income'), (17, '15-20% of Income'), (50, '20%-100% of Income')]),
        ),
    ]
