# Generated by Django 5.2 on 2025-04-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_clientprofile_investment_horizon_years_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='investment_horizon_years',
            new_name='investment_horizon',
        ),
    ]
