# Generated by Django 5.2 on 2025-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_investment_horizon_years_clientprofile_investment_horizon'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='avatar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='annual_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='familiarity_with_market',
            field=models.IntegerField(blank=True, choices=[(0, 'Not familiar at all'), (1, 'Somewhat familiar'), (2, 'Moderately familiar'), (3, 'Very familiar'), (4, 'Expert level familiarity')], null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='investment_horizon',
            field=models.IntegerField(blank=True, choices=[(12, 'Less than 1 year'), (36, '1 to 3 years'), (60, '3 to 5 years'), (120, '5 to 10 years'), (240, 'More than 10 years')], null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='percentage_comforatable_savings',
            field=models.IntegerField(blank=True, choices=[(3, '0-5% of Income'), (8, '5-10% of Income'), (13, '10-15% of Income'), (17, '15-20% of Income'), (50, '20%-100% of Income')], null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_asset_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='primary_investment_goal',
            field=models.CharField(blank=True, choices=[('protecting_your_principal', 'Protecting Your Principal'), ('income_generation', 'Income Generation'), ('balanced_growth_and_income', 'Balanced Growth and Income'), ('Growth_oriented_investing', 'Growth-Oriented Investing'), ('aggressive_growth', 'Aggressive Growth')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='risk_tolerance',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='target_return',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
