# Generated by Django 5.2 on 2025-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clientprofile_address_clientprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
