# Generated by Django 5.2 on 2025-04-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_clientprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='preferred_asset_types',
            new_name='preferred_asset',
        ),
    ]
