# Generated by Django 5.2 on 2025-04-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_preferred_asset_types_clientprofile_preferred_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='preferred_asset',
            new_name='preferred_assets',
        ),
    ]
