# Generated by Django 5.2 on 2025-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliometrics',
            old_name='diversification_index',
            new_name='annulaized_volatility',
        ),
        migrations.AddField(
            model_name='portfoliometrics',
            name='maximum_drawdown',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
