# Generated by Django 5.2 on 2025-04-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_rename_diversification_index_portfoliometrics_annulaized_volatility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliometrics',
            name='final_equity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
