# Generated by Django 5.2 on 2025-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_portfoliometrics_final_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='initial_equity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
