# Generated by Django 5.2 on 2025-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_portfolio_initial_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='return_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
