# Generated by Django 5.2 on 2025-04-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_portfolioasset_return_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioasset',
            name='return_percent',
        ),
    ]
