# Generated by Django 5.2 on 2025-04-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0007_remove_portfolioasset_return_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfoliometrics",
            name="maximum_drawdown",
        ),
    ]
