# Generated by Django 5.2 on 2025-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_price',
        ),
        migrations.AddField(
            model_name='asset',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AssetHistoricalData',
        ),
    ]
