# Generated by Django 5.2 on 2025-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_current_price_asset_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
