# create_assets.py inside your app's "management/commands" folder

from django.core.management.base import BaseCommand
from assets.models import Asset

class Command(BaseCommand):
    help = 'Bulk create Asset entries for stock symbols'

    def handle(self, *args, **kwargs):
        symbols = """
        A AAP AAPL ABT ACN ADBE ADI ADM ADP ADSK AEE AEP AES AFL AIG AIV AIZ AJG AKAM ALB ALGN ALK ALL AMAT AMD AME AMGN AMT AMZN ANSS AON AOS APA APD APH ARE ATO AVB AVY AXP AZO BA BAC BAX BBY BDX BEN BIIB BIO BK BKNG BKR BLK BMY BSX BWA BXP C CAG CAH CAT CB CBRE CCI CCL CDNS CE CHD CHRW CI CINF CL CLX CMA CMCSA CME CMI CMS CNC CNP COF COO COP COST CPB CPRT CRM CSCO CSX CTAS CTSH CVS CVX D DD DE DGX DHI DHR DIS DLR DLTR DOV DPZ DRI DTE DUK DVA DVN DXC DXCM EA EBAY ECL ED EFX EIX EL EMN EMR EOG EQIX EQR ES ESS ETN ETR EVRG EW EXC EXPD EXPE EXR F FAST FCX FDX FE FFIV FIS FITB FLS FMC FRT FTI FTNT GD GE GILD GIS GL GLW GOOG GOOGL GPC GPN GRMN GS GWW HAL HAS HBAN HD HES HIG HOLX HON HPQ HRB HRL HSIC HST HSY HUM IBM IDXX IEX IFF ILMN INCY INTC INTU IP IPG IRM ISRG IT ITW IVZ J JBHT JCI JKHY JNJ JNPR JPM K KEY KIM KLAC KMB KMX KO KR KSS L LEG LEN LH LHX LIN LKQ LLY LMT LNC LNT LOW LRCX LUV LVS MAA MAR MAS MCD MCHP MCK MCO MDLZ MDT MET MGM MHK MKC MKTX MLM MMC MMM MNST MO MOS MRK MS MSFT MSI MTB MTD MU NDAQ NEE NEM NFLX NI NKE NOC NOV NRG NSC NTAP NTRS NUE NVDA NVR NWL O ODFL OKE OMC ORCL ORLY OXY PAYX PCAR PEG PEP PFE PFG PG PGR PH PHM PKG PLD PNC PNR PNW PPG PPL PRGO PRU PSA PVH PWR QCOM RCL REG REGN RF RHI RJF RL RMD ROK ROL ROP ROST RSG RTX SBAC SBUX SCHW SEE SHW SJM SLB SLG SNA SNPS SO SPG SPGI SRE STE STT STX STZ SWK SWKS SYK SYY T TAP TDY TFC TFX TGT TJX TMO TMUS TPR TROW TRV TSCO TSN TT TTWO TXN TXT TYL UAA UDR UHS UNH UNM UNP UPS URI USB VFC VLO VMC VNO VRSN VRTX VTR VZ WAB WAT WBA WDC WEC WELL WFC WHR WM WMB WMT WRB WST WY WYNN XEL XOM XRAY XRX YUM ZBH ZBRA ZION
        """.split()

        assets = [
            Asset(
                name=symbol,
                symbol=symbol,
                asset_type='stock',
                exchange='NYSE'  # or whichever exchange you prefer
            )
            for symbol in symbols
        ]

        Asset.objects.bulk_create(assets, ignore_conflicts=True)
        self.stdout.write(self.style.SUCCESS(f'Successfully created {len(assets)} stock assets.'))
